### ISSUE TITLE
Add to platformio registry

### ISSUE THREAD

**Issue by PhilippMolitor** [vortigont/MuiPlusPlus#1]
Hey, thanks for creating this library. You should add it to the PlatformIO registry to make it easily accessible there!

See: https://docs.platformio.org/en/latest/librarymanager/creating.html

**Comment by vortigont** [comment]
Hi @PhilippMolitor,
sure, I will add it! It's under development now and no examples so far.
If you are to use it, I'll appreciate and kind of feedback.
Thanks!

**Comment by PhilippMolitor** [comment]
Hey, I came here from my issue in the U8g2 issue about C++ semantics, I am very certain I will use your library for my current project. Could you maybe take the time to add 1-2 quick and dirty examples just to have something to start from? Looking everything up from the linked repository is a bit messy. 

Thanks a lot for your work so far!

**Comment by vortigont** [comment]
Agreed. I'll come up with something to start shortly. Then you can check how it will work for you.

**Comment by vortigont** [comment]
@PhilippMolitor I've added a couple of examples, pls check if that would be helpfull.
Feel free to open a discussion if that all is too messy.

**Comment by PhilippMolitor** [comment]
Thanks, looks great! There is no chance you will add support for Adafruit GFX as well, is there?

**Comment by vortigont** [comment]
Adafruit GFX is out of luck. It's too old fashion lib without unicode fonts, required methods to determine letter/word sizing, positioning, etc...
U8g2 is great 'cause it already has things like inverted printing, boxes around text, etc... With Adafruit all this has to be implemented from scratch.
If I needed colored screen support I would rather considered [Arduino_GFX](https://github.com/moononournation/Arduino_GFX). Almost same API as Adafruit but with a bit more modern implementation and support for unicode fonts from U8g2.
Currently I do not have projects for color screens in scope, so maybe later...
But any contributions are welcome )

**Comment by vortigont** [comment]
P.S. [lvgl](https://lvgl.io/) might possibly be a good option, but I've never worked with it so far.

**Comment by vortigont** [comment]
Available here - [MuiPlusPlus](https://registry.platformio.org/libraries/vortigont/MuiPlusPlus)
